spring:
  datasource:
    url: jdbc:postgresql://postgres:nfRWcOxyJSVePRWCPFnkpFHeOEUFRUZu@postgres.railway.internal:5432/railway
    username: postgres
    password: nfRWcOxyJSVePRWCPFnkpFHeOEUFRUZu
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update





